# Generated by Django 5.1.5 on 2025-02-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
